import type { NormalizedWord, RecordingAnalysis } from '@/types/api';

export const MOCK_TRANSCRIPT =
  'So, um, I think that, you know, public speaking is, uh, really important because, like, it helps you communicate your ideas more clearly and, um, connect with your audience.';

export const MOCK_WORDS: NormalizedWord[] = [
  { index: 0, displayText: 'So', startChar: 0, endChar: 1, confidence: 0.99 },
  { index: 1, displayText: 'um', startChar: 4, endChar: 5, confidence: 0.97 },
  { index: 2, displayText: 'I', startChar: 8, endChar: 8, confidence: 0.99 },
  {
    index: 3,
    displayText: 'think',
    startChar: 10,
    endChar: 14,
    confidence: 0.98,
  },
  {
    index: 4,
    displayText: 'that',
    startChar: 16,
    endChar: 19,
    confidence: 0.99,
  },
  {
    index: 5,
    displayText: 'you',
    startChar: 22,
    endChar: 24,
    confidence: 0.98,
  },
  {
    index: 6,
    displayText: 'know',
    startChar: 26,
    endChar: 29,
    confidence: 0.97,
  },
  {
    index: 7,
    displayText: 'public',
    startChar: 32,
    endChar: 37,
    confidence: 0.99,
  },
  {
    index: 8,
    displayText: 'speaking',
    startChar: 39,
    endChar: 46,
    confidence: 0.98,
  },
  { index: 9, displayText: 'is', startChar: 48, endChar: 49, confidence: 0.99 },
  {
    index: 10,
    displayText: 'uh',
    startChar: 52,
    endChar: 53,
    confidence: 0.96,
  },
  {
    index: 11,
    displayText: 'really',
    startChar: 56,
    endChar: 61,
    confidence: 0.99,
  },
  {
    index: 12,
    displayText: 'important',
    startChar: 63,
    endChar: 71,
    confidence: 0.99,
  },
  {
    index: 13,
    displayText: 'because',
    startChar: 73,
    endChar: 79,
    confidence: 0.98,
  },
  {
    index: 14,
    displayText: 'like',
    startChar: 82,
    endChar: 85,
    confidence: 0.95,
  },
  {
    index: 15,
    displayText: 'it',
    startChar: 88,
    endChar: 89,
    confidence: 0.99,
  },
  {
    index: 16,
    displayText: 'helps',
    startChar: 91,
    endChar: 95,
    confidence: 0.99,
  },
  {
    index: 17,
    displayText: 'you',
    startChar: 97,
    endChar: 99,
    confidence: 0.99,
  },
  {
    index: 18,
    displayText: 'communicate',
    startChar: 101,
    endChar: 111,
    confidence: 0.98,
  },
  {
    index: 19,
    displayText: 'your',
    startChar: 113,
    endChar: 116,
    confidence: 0.99,
  },
  {
    index: 20,
    displayText: 'ideas',
    startChar: 118,
    endChar: 122,
    confidence: 0.99,
  },
  {
    index: 21,
    displayText: 'more',
    startChar: 124,
    endChar: 127,
    confidence: 0.99,
  },
  {
    index: 22,
    displayText: 'clearly',
    startChar: 129,
    endChar: 135,
    confidence: 0.99,
  },
  {
    index: 23,
    displayText: 'and',
    startChar: 137,
    endChar: 139,
    confidence: 0.99,
  },
  {
    index: 24,
    displayText: 'um',
    startChar: 142,
    endChar: 143,
    confidence: 0.96,
  },
  {
    index: 25,
    displayText: 'connect',
    startChar: 146,
    endChar: 152,
    confidence: 0.99,
  },
  {
    index: 26,
    displayText: 'with',
    startChar: 154,
    endChar: 157,
    confidence: 0.99,
  },
  {
    index: 27,
    displayText: 'your',
    startChar: 159,
    endChar: 162,
    confidence: 0.99,
  },
  {
    index: 28,
    displayText: 'audience',
    startChar: 164,
    endChar: 171,
    confidence: 0.99,
  },
];

export const MOCK_ANALYSIS_RESULT: RecordingAnalysis = {
  transcript: MOCK_TRANSCRIPT,
  words: MOCK_WORDS,
  duration: 15,
  fillers: [
    { startIndex: 1, displayText: 'um', confidence: 0.95 },
    { startIndex: 5, displayText: 'you know', confidence: 0.92 },
    { startIndex: 10, displayText: 'uh', confidence: 0.97 },
    { startIndex: 14, displayText: 'like', confidence: 0.88 },
    { startIndex: 24, displayText: 'um', confidence: 0.94 },
  ],
  fillerStats: {
    totalFillers: 5,
    totalWords: 29,
    fillerPercentage: 17.2,
    fillersPerMinute: 20,
    topFillers: [
      { text: 'um', count: 2 },
      { text: 'you know', count: 1 },
      { text: 'uh', count: 1 },
      { text: 'like', count: 1 },
    ],
  },
  clarityScore: { score: 72, version: '1.0', rawScore: 0.72 },
};

export const EMPTY_ANALYSIS_RESULT: RecordingAnalysis = {
  transcript: '',
  words: [],
  duration: 0,
  fillers: [],
  fillerStats: {
    totalFillers: 0,
    totalWords: 0,
    fillerPercentage: 0,
    fillersPerMinute: 0,
    topFillers: [],
  },
  clarityScore: null,
};
